#!/usr/bin/env python3
# Copyright 2025 Alexander Alten (novatechflow), NovaTechflow (novatechflow.com).
# This project is supported and financed by Scalytics, Inc. (www.scalytics.io).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import pathlib
import subprocess
import sys

LICENSE_MARKER = "Apache License, Version 2.0"

CHECK_EXTS = {
    ".go",
    ".proto",
    ".sh",
    ".bash",
    ".zsh",
    ".yaml",
    ".yml",
    ".toml",
    ".mk",
    ".env",
    ".ini",
    ".cfg",
    ".conf",
    ".txt",
    ".md",
}

SPECIAL_FILENAMES = {
    "Makefile",
    "Dockerfile",
    ".gitignore",
    ".dockerignore",
}

SKIP_PREFIXES = (
    ".git/",
    "bin/",
    ".gocache/",
    ".gopath/",
    ".tmp-controller-runtime/",
    ".vscode/",
    "third_party/",
    "pkg/gen/",
)

SKIP_FILES = {"LICENSE", "NOTICE"}


def git_files() -> list[str]:
    result = subprocess.run(
        ["git", "ls-files"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=True,
    )
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def should_check(path: pathlib.Path, rel: str) -> bool:
    if rel in SKIP_FILES:
        return False
    if any(rel.startswith(prefix) for prefix in SKIP_PREFIXES):
        return False
    if path.name in SPECIAL_FILENAMES:
        return True
    return path.suffix in CHECK_EXTS


def is_generated(text: str) -> bool:
    return "Code generated by" in text or "DO NOT EDIT." in text


def is_binary(path: pathlib.Path) -> bool:
    try:
        data = path.read_bytes()
    except OSError:
        return True
    return b"\0" in data


def main() -> int:
    repo = pathlib.Path(__file__).resolve().parents[1]
    missing = []
    for rel in git_files():
        if rel.startswith(tuple(SKIP_PREFIXES)):
            continue
        path = repo / rel
        if not should_check(path, rel):
            continue
        if is_binary(path):
            continue
        text = path.read_text(encoding="utf-8")
        if is_generated(text):
            continue
        if LICENSE_MARKER not in text:
            missing.append(rel)
    if missing:
        print("Missing Apache 2.0 license header in:")
        for rel in missing:
            print(f"- {rel}")
        return 1
    print("All checked files include Apache 2.0 license headers.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
