#!/usr/bin/env python3
# Copyright 2025 Alexander Alten (novatechflow), NovaTechflow (novatechflow.com).
# This project is supported and financed by Scalytics, Inc. (www.scalytics.io).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import pathlib
import subprocess
import sys

YEAR = "2025"
HOLDER = "Alexander Alten (novatechflow), NovaTechflow (novatechflow.com)."
SUPPORT = "This project is supported and financed by Scalytics, Inc. (www.scalytics.io)."

LICENSE_LINES = [
    f"Copyright {YEAR} {HOLDER}",
    SUPPORT,
    "",
    'Licensed under the Apache License, Version 2.0 (the "License");',
    "you may not use this file except in compliance with the License.",
    "You may obtain a copy of the License at",
    "",
    "    http://www.apache.org/licenses/LICENSE-2.0",
    "",
    "Unless required by applicable law or agreed to in writing, software",
    'distributed under the License is distributed on an "AS IS" BASIS,',
    "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.",
    "See the License for the specific language governing permissions and",
    "limitations under the License.",
]

LINE_COMMENT_EXTS = {
    ".go": "//",
    ".proto": "//",
    ".sh": "#",
    ".bash": "#",
    ".zsh": "#",
    ".yaml": "#",
    ".yml": "#",
    ".toml": "#",
    ".mk": "#",
    ".env": "#",
    ".ini": "#",
    ".cfg": "#",
    ".conf": "#",
    ".txt": "#",
}

MD_EXTS = {".md"}

SPECIAL_FILENAMES = {
    "Makefile": "#",
    "Dockerfile": "#",
    ".gitignore": "#",
    ".dockerignore": "#",
}

SKIP_PREFIXES = (
    ".git/",
    "bin/",
    ".gocache/",
    ".gopath/",
    ".tmp-controller-runtime/",
    ".vscode/",
    "third_party/",
    "pkg/gen/",
)

SKIP_FILES = {"LICENSE", "NOTICE"}


def file_comment_style(path: pathlib.Path) -> str | None:
    if path.name in SKIP_FILES:
        return None
    if path.name in SPECIAL_FILENAMES:
        return SPECIAL_FILENAMES[path.name]
    if path.suffix in MD_EXTS:
        return "<!-- -->"
    if path.suffix in LINE_COMMENT_EXTS:
        return LINE_COMMENT_EXTS[path.suffix]
    return None


def build_header(style: str) -> str:
    if style == "<!-- -->":
        body = "\n".join(LICENSE_LINES)
        return f"<!--\n{body}\n-->\n\n"
    lines = "\n".join(f"{style} {line}".rstrip() for line in LICENSE_LINES)
    return f"{lines}\n\n"


def has_header(text: str) -> bool:
    return "Apache License, Version 2.0" in text


def is_generated(text: str) -> bool:
    return "Code generated by" in text or "DO NOT EDIT." in text


def is_binary(path: pathlib.Path) -> bool:
    try:
        data = path.read_bytes()
    except OSError:
        return True
    return b"\0" in data


def git_files() -> list[str]:
    result = subprocess.run(
        ["git", "ls-files"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=True,
    )
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def main() -> int:
    repo = pathlib.Path(__file__).resolve().parents[1]
    changed = 0
    for rel in git_files():
        if any(rel.startswith(prefix) for prefix in SKIP_PREFIXES):
            continue
        path = repo / rel
        style = file_comment_style(path)
        if style is None:
            continue
        if is_binary(path):
            continue
        text = path.read_text(encoding="utf-8")
        if is_generated(text) or has_header(text):
            continue
        header = build_header(style)
        path.write_text(header + text, encoding="utf-8")
        changed += 1
    if changed:
        print(f"Added license headers to {changed} files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
